### ISSUE TITLE
SyntaxError Unexpected token export

### ISSUE THREAD

**Issue by begueradj** [shaqaruden/vuetify2.x-datetime-picker#1]
Is this possible to use within Nuxt.js ?

I have a Nuxt.js application which also uses VuetifyJs.

I followed the steps mentioned here:

`yarn add vuetify2.x-datetime-picker`

Then I created a **plugins/mypicker.js** file:

```javascript
import Vue from 'vue'
import VDateTimePicker from 'vuetify2.x-datetime-picker'

Vue.use(VDateTimePicker)
```

In nuxt.config.js I ask Nuxt.js to use it:

```javascript
plugins: [ '@/plugins/mypicker'],
```

When I type on Terminal: yarn run dev the application launches successfully without errors, but when I open a browser tab to hit: http://localhost:3000, I see this error message on the webpage:

> 
> SyntaxError
> Unexpected token export

How to fix this ?

Here is a Github link to [reproduce the bug](https://github.com/begueradj/vuetify2-datetime-picker).

**Comment by shaqaruden** [comment]
can you recreate in codepen or jsfiddle?

**Comment by begueradj** [comment]
I shared a small [Github repo](https://github.com/begueradj/vuetify2-datetime-picker) that reproduces the bug as described above. Thank you @shaqaruden

**Comment by begueradj** [comment]
This needs transpilation, so it is not an issue
